### ISSUE TITLE
Bug: Rename javascript.js to script.js or index.js

### ISSUE THREAD

**Issue by moeenio** [Accio1/SSE#1]
**Describe the solution you'd like**
The main JS file is called javascript.js. You should rename it to script.js or index.js because it's not javascript itself.

**Additional context**
BTW, you should change the original title for the Feature request template

**Comment by Accio1** [comment]
> The main JS file is called javascript.js. You should rename it to script.js or index.js because it's not javascript itself.


I don't see why this has to be renamed. I only have one .js file, and naming it javascript.js doesn't cause any issues anywhere else.

> BTW, you should change the original title for the Feature request template


Why? It currently says "Feature Request:", and then the person can type the feature that they want after the colon.

**Comment by moeenio** [comment]
Idk why, but it said "bug:" for me (the issue template).

For renaming this is just more common practice

**Comment by Accio1** [comment]
> Idk why, but it said "bug:" for me (the issue template).


There are two issue templates. One is for bugs, and one is for features. The bug report one has "Bug:", as the title, and the feature request one has "Feature Request:" as the title.

**Comment by moeenio** [comment]
I used the Feature Request one, light be just a bug from GitHub.

**Comment by Accio1** [comment]
It works fine for me

**Comment by moeenio** [comment]
Ok, but for renaming the file

**Comment by Accio1** [comment]
That's low priority, I might change it in the next update.

**Comment by moeenio** [comment]
Not be mean, but it doesn't take long.

**Comment by Accio1** [comment]
I don't want to make a commit just to change that.

**Comment by moeenio** [comment]
That's not bad practice or whatever

**Comment by Accio1** [comment]
Fixed in #3
